trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: notes-backend
  dockerRegistryServiceConnection: acr-service-connection

stages:
- stage: BuildAndPush
  displayName: Build and Push Backend Image

  jobs:
  - job: DockerBuild
    displayName: Docker Build Job

    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push Backend Image

      inputs:
        command: buildAndPush
        repository: $(imageName)

        dockerfile: backend/Dockerfile
        buildContext: .

        containerRegistry: $(dockerRegistryServiceConnection)

        tags: |
          latest